### ISSUE TITLE
npm run serve through error

### ISSUE THREAD

**Issue by jvaranam** [mirkonasato/angular2-course-webpack-starter#4]
Hi Mirkonasato,

While i run npm install one dependency skipped "chokidar /  fsevent"  this due to windows os

But while i run npm run serve, i was getting the following error, Plz help me to sort out this issue.

70% 2/2 build modulesevents.js:141
     throw er; // Unhandled 'error' event

Error: listen EADDRINUSE 127.0.0.1:8080
at Obect.exports._errnoException (util.js:878:11)

**Comment by BenWildeman** [comment]
EADDRINUSE means that port 8080 is already in use, try setting the port to something else

**Comment by mirkonasato** [comment]
What NitroGhost said; not an issue with this project.
